### ISSUE TITLE
Add LICENCE

### ISSUE THREAD

**Issue by andybak** [SeongSeopLIm/Unity-Runtime-ply-loader#2]
Hiya,

I'm looking round for code to use to add point cloud support to Open Brush ( https://github.com/icosa-gallery/open-brush ) but before I even look at a project I need to check if the licence is compatible. 

What did you have in mind for the licence for this (for the parts you've added - I'll obviously check pcx etc for the licences that cover that)?

**Comment by SeongSeopLIm** [comment]
Added MIT License
